fail CMake for GCC < 4.9.0
Somehow GCC 4.8.x is not able to deal with the delegating ctors of
Encapsulation with conditional specialization.
Thus we have to require at least 4.9.0.

This was tested with GCC 4.8.5 and 4.9.3.

Detailed error message with GCC 4.8.5:

In file included from /home/t.klatt/projects/PFASST/include/pfasst/encap/vector.hpp:108:0,
                 from /home/t.klatt/projects/PFASST/include/pfasst/contrib/fft.hpp:16,
                 from /home/t.klatt/projects/PFASST/tests/contrib/test_fft.cpp:17:
/home/t.klatt/projects/PFASST/src/pfasst/encap/vector_impl.hpp: In instantiation of ‘pfasst::encap::Encapsulation<EncapsulationTrait, typename std::enable_if<std::is_same<std::vector<typename EncapsulationTrait::spacial_type>, typename EncapsulationTrait::data_type>::value>::type>::Encapsulation(const typename EncapsulationTrait::data_type&) [with EncapsulationTrait = pfasst::vector_encap_traits<double, double>; typename std::enable_if<std::is_same<std::vector<typename EncapsulationTrait::spacial_type>, typename EncapsulationTrait::data_type>::value>::type = void; typename EncapsulationTrait::data_type = std::vector<double>]’:
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Args = {std::vector<double, std::allocator<double> >}; _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Args = {std::vector<double, std::allocator<double> >}; _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Args = {std::vector<double, std::allocator<double> >}; _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr_base.h:400:38:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {std::vector<double, std::allocator<double> >}; _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Sp_counted_ptr_inplace<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>, std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >, (__gnu_cxx::_Lock_policy)2u>; _Args = {const std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >, std::vector<double, std::allocator<double> >}; _Tp = std::_Sp_counted_ptr_inplace<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>, std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >, (__gnu_cxx::_Lock_policy)2u>]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/alloc_traits.h:254:4:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr_base.h:503:37:   required from ‘std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; _Args = {std::vector<double, std::allocator<double> >}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr_base.h:957:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; _Args = {std::vector<double, std::allocator<double> >}; _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr.h:316:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; _Args = {std::vector<double, std::allocator<double> >}; _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr.h:598:39:   required from ‘std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Alloc = std::allocator<pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void> >; _Args = {std::vector<double, std::allocator<double> >}]’
/data/opt/toolchains/gcc/4.8.5/include/c++/4.8.5/bits/shared_ptr.h:614:42:   required from ‘std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>; _Args = {std::vector<double, std::allocator<double> >}]’
/home/t.klatt/projects/PFASST/tests/contrib/test_fft.cpp:96:82:   required from here
/home/t.klatt/projects/PFASST/src/pfasst/encap/vector_impl.hpp:38:43: error: no matching function for call to ‘pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>::Encapsulation()’
       : Encapsulation<EncapsulationTrait>()
                                           ^
/home/t.klatt/projects/PFASST/src/pfasst/encap/vector_impl.hpp:38:43: note: candidates are:
/home/t.klatt/projects/PFASST/src/pfasst/encap/vector_impl.hpp:30:5: note: pfasst::encap::Encapsulation<EncapsulationTrait, typename std::enable_if<std::is_same<std::vector<typename EncapsulationTrait::spacial_type>, typename EncapsulationTrait::data_type>::value>::type>::Encapsulation(const typename EncapsulationTrait::data_type&) [with EncapsulationTrait = pfasst::vector_encap_traits<double, double>; typename std::enable_if<std::is_same<std::vector<typename EncapsulationTrait::spacial_type>, typename EncapsulationTrait::data_type>::value>::type = void; typename EncapsulationTrait::data_type = std::vector<double>]
     Encapsulation<
     ^
/home/t.klatt/projects/PFASST/src/pfasst/encap/vector_impl.hpp:30:5: note:   candidate expects 1 argument, 0 provided
In file included from /home/t.klatt/projects/PFASST/include/pfasst/contrib/fft.hpp:16:0,
                 from /home/t.klatt/projects/PFASST/tests/contrib/test_fft.cpp:17:
/home/t.klatt/projects/PFASST/include/pfasst/encap/vector.hpp:24:11: note: pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>::Encapsulation(const pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>&)
     class Encapsulation<EncapsulationTrait,
           ^
/home/t.klatt/projects/PFASST/include/pfasst/encap/vector.hpp:24:11: note:   candidate expects 1 argument, 0 provided
/home/t.klatt/projects/PFASST/include/pfasst/encap/vector.hpp:24:11: note: pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>::Encapsulation(pfasst::encap::Encapsulation<pfasst::vector_encap_traits<double, double>, void>&&)
/home/t.klatt/projects/PFASST/include/pfasst/encap/vector.hpp:24:11: note:   candidate expects 1 argument, 0 provided